### ISSUE TITLE
Forgot icon for "pinned tweet"

### ISSUE THREAD

**Issue by alextanasie** [comanandrei1993/twitter-mock-up#1]
![Screenshot 2020-03-06 at 16 30 46](https://user-images.githubusercontent.com/18068016/76092356-ee568680-5fc7-11ea-8032-276bf828e43e.png)

**Comment by comanandrei1993** [comment]
- added the /images/icons/icon-pinned.svg as background image to the pinned tweet
- added new light gray color to variables for icon-pinned 
- in the pinned::before pseudo-element, added "white-space: pre" and spaces to the content attribute
